// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 27/5/2025, 7:27:21 pm
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["D:/techbank-v2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/techbank-v2/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/techbank-v2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/techbank-v2/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/techbank-v2/plugins/**/*.{js,ts,mjs}","D:/techbank-v2/composables/**/*.{js,ts,mjs}","D:/techbank-v2/utils/**/*.{js,ts,mjs}","D:/techbank-v2/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/techbank-v2/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/techbank-v2/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/techbank-v2/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;